#!/bin/sh -e
cd `dirname $0`/..

c=$1
while [ 0 -ne $# ]
  do
    case $c in
      -*d) pdump=1; c=${c%?};;
      -*a) paddr=1; c=${c%?};;
      -*s) psize=1; c=${c%?};;
      -*e) pend=1; c=${c%?};;
      -) shift; c=$1;;
      *) ver=`tools/v-short.util $c`; shift; c=$1;;
    esac
done

file=`hidden/have-version $ver`/pico8
nm -S $file | grep -w pico8_preprocess | tr [a-f] [A-F] | (
  read start size T PICO8_PREPROCESS
  end=`dc -e "16dio $start $size +n"`

  [ -n "$paddr" ] && printf 0x%s\\n `dc -e "16dio $start n"`
  [ -n "$psize" ] && printf 0x%s\\n `dc -e "16dio $size n"`
  [ -n "$pend"  ] && printf 0x%s\\n `dc -e "16dio $end n"`

  [ -n "$pdump" ] && objdump -d $file \
      --section=.text \
      --start-address="0x$start" \
      --stop-address="0x$end"
)
